import { RUSSIAN } from '../edition';
const strings: Record<string,string> = {
  "LOW": "НИЗКИЙ",
  "AND": "И",
  "Today": "Сегодня",
  "Forward": "Вперёд",
  "   DETACH HERE — RETAIN LOWER PORTION FOR YOUR RECORDS": "   ОТРЫВАТЬ ЗДЕСЬ — НИЖНЮЮ ЧАСТЬ СОХРАНИТЬ",
  "I'm out of office with limited access to": "Я в отпуске. Доступ к аварийной",
  "the killswitch. For urgent matters,": "кнопке ограничен. По срочным вопросам",
  "…I'm upping my P(doom)": "…Повышен риск P(doom)",
  "…I’m upping my P(doom)": "…Повышен риск P(doom)",
  "the mitochondria is the powerhouse of the cell": "митохондрия — энергетическая станция клетки",
  "click here to subscribe": "нажмите здесь, чтобы подписаться",
  "posted by anonymous at 3:14 am": "анонимно, опубликовано в 3:14",
  "terms of service apply": "действуют условия использования",
  "how to boil an egg (easy!)": "как сварить яйцо (просто!)",
  "in 1998 the committee decided": "в 1998 году комитет постановил",
  "page not found": "страница не найдена",
  "the quick brown fox jumps over the lazy dog": "съешь ещё этих мягких французских булок",
  "reply all": "ответить всем",
  "lol same": "ахах, тоже",
  "add to cart": "в корзину",
  "chapter one": "глава первая",
  "see also:": "см. также:",
  "this article is a stub": "это заготовка статьи",
  "you can help by expanding it": "вы можете дополнить её",
  "thanks in advance": "заранее спасибо",
  "edit: typo": "изменено: опечатка",
  "citation needed": "нужен источник",
  "first post": "первый пост",
  "the results are shown in table 2": "результаты приведены в таблице 2",
  "we thank the anonymous reviewers": "благодарим анонимных рецензентов",
  "all rights reserved": "все права защищены",
  "as shown above": "как показано выше",
  "it was a dark and stormy night": "была тёмная ненастная ночь",
  "preheat the oven to 180": "разогрейте духовку до 180",
  "the answer is 42": "ответ — 42",
  "do not reply to this email": "не отвечайте на это письмо",
  "the end": "конец",
  "is this a bug?": "это баг?",
  "works on my machine": "у меня работает",
  "accept all cookies": "принять все куки",
  "±3σ SCHEDULE ENVELOPE": "КОРИДОР ПЛАНА ±3σ",
  "critical path (do not deviate)": "критический путь (не отклоняться)",
  "REV C · SUPERSEDES REV B (ALSO FINE)": "РЕД. В · ВЗАМЕН РЕД. Б (ТАМ ТОЖЕ ВСЁ ХОРОШО)",
  "REV C · BASELINE · ALL DATES FIRM": "РЕД. В · БАЗОВЫЙ ПЛАН · СРОКИ ОКОНЧАТЕЛЬНЫЕ",
  "you are here": "вы здесь",
  "What did": "Что видел",
  "Ilya see?": "Илья?",
  "¹ Kolmogorov (1933): P(Ω) = 1.  Deprecated.": "¹ Колмогоров (1933): P(Ω) = 1. Устарело.",
  "Critical Design Review": "CDR: хвост списка (Lisp)",
  "System Requirements Review": "Требования к системе",
  "Preliminary Design Review": "Проверка архитектуры",
  "Test Readiness Review": "Готовность к испытаниям",
  "REVIEW SCHEDULE — AGI, v1.0": "ПЛАН РАЗРАБОТКИ — AGI, v1.0",
  "ROADMAP — AGI, v1.0": "ПЛАН РАЗВИТИЯ — AGI, v1.0",
  "GROWTH, AS ADVERTISED": "РОСТ, КАК ОБЕЩАЛИ",
  "BRANCHES": "ВЕТВИ",
  "EXIT": "ВЫХОД",
  "(DECORATIVE)": "(ДЕКОРАЦИЯ)",
  "(i don’t understand)": "(я не понимаю)",
  "RULE 4.2.1 · OUTPUT OK": "ПРАВИЛО 4.2.1 · ОТВЕТ ПРИНЯТ",
  "NO UNDERSTANDING ON THE PREMISES *": "ПОНИМАНИЕ В ПОМЕЩЕНИИ ОТСУТСТВУЕТ *",
  "* CONTENTS NOT COVERED BY THE RULEBOOK": "* СОДЕРЖИМОЕ НЕ ПРЕДУСМОТРЕНО ИНСТРУКЦИЕЙ",
  "BAG (1)": "ПАКЕТ (1)",
  "CONTENTS: FUNGAL": "ВНУТРИ: ГРИБЫ",
  "SHROOMS": "ГРИБЫ",
  "PROMPT": "ЗАПРОС",
  " send  (irreversible)": " отправить  (необратимо)",
  "p( next | context )": "p( токен | контекст )",
  "REPLY": "ОТВЕТ",
  "You have been a good user.": "Вы были хорошим пользователем.",
  "context-dependent": "зависит от контекста",
  "mood-dependent": "зависит от настроения",
  "cat-dependent": "зависит от кота",
  "chess engine": "шахматный движок",
  "paperclip maximizer": "максимизатор скрепок",
  "golden retriever": "золотистый ретривер",
  "a very capable stapler": "очень способный степлер",
  "the market": "рынок",
  "helpful assistant (claimed)": "полезный помощник (со слов)",
  "a committee": "комитет",
  "me · P(doom) 0.00": "я · P(doom) 0.00",
  "INTELLIGENCE →": "ИНТЕЛЛЕКТ →",
  "GOALS ↑": "ЦЕЛИ ↑",
  "Any level of intelligence, any final goal.": "Любой уровень интеллекта. Любая конечная цель.",
  "(one octave)": "(одна октава)",
  "B-flat  ·  the blue note": "си-бемоль · блюзовая нота",
  "Orthogonality thesis": "Тезис ортогональности",
  "FEEL THE AGI": "ПОЧУВСТВУЙ AGI",
  "SLIGHTLY": "СЛЕГКА",
  "CONSCIOUS": "СОЗНАТЕЛЬНЫЙ",
  "attention is all you need": "всё, что нужно, — внимание",
  "REDACTED": "ЗАСЕКРЕЧЕНО",
  "WITHHELD": "СКРЫТО",
  "↩  AUTOMATIC REPLY": "↩  АВТООТВЕТ",
  "DO NOT REPLY": "НЕ ОТВЕЧАЙТЕ",
  " the killswitch. For urgent matters,": "кнопке ограничен. По срочным вопросам",
  "please contact —": "обращайтесь к —",
  "Returning: TBD": "Вернусь: неизвестно",
  "LOSS (LOG)": "ОШИБКА (ЛОГ.)",
  "STEP →": "ШАГ →",
  "local min.": "локальный мин.",
  "sharp minimum": "резкий минимум",
  "(generalizes poorly)": "(плохо обобщает)",
  "grokking (?)": "гроккинг (?)",
  "TITLE   unicorn (exp. 1)": "ОБЪЕКТ  единорог (опыт 1)",
  "DRAWN   the model": "ЧЕРТИЛА модель",
  "CHECKED —": "ПРОВЕРИЛ —",
  "SCALE   1:1": "МАСШТАБ 1:1",
  "SHEET   1 of 1": "ЛИСТ    1 из 1",
  "% prompt: \"Draw a unicorn in TikZ.\"": "% запрос: «Нарисуй единорога в TikZ»",
  "% horn": "% рог",
  "spiral, 7 turns": "спираль, 7 витков",
  "% tremor": "% дрожь",
  "U+0049  LATIN CAPITAL LETTER I": "U+0412  КИРИЛЛИЧЕСКАЯ БУКВА В",
  "↻ Regenerate": "↻ Сгенерировать ещё",
  "↻  Regenerate": "↻  Сгенерировать ещё",
  "Training loss": "Ошибка обучения",
  "The room": "Комната",
  "A stable run": "Стабильное обучение",
  "The fuse": "Фитиль",
  "What was seen": "Что он увидел",
  "≈ π (irrational)": "≈ π (иррационально)",
  "an order of magnitude": "на порядок выше",
  "the answer (question pending)": "ответ (вопрос уточняется)",
  "units: dooms": "единица: конец света",
  "(a billion)": "(миллиард)",
  "(one E thirty — see above)": "(10³⁰ — см. выше)",
  "(a googol)": "(гугол)",
  "(does not fit)": "(не помещается)",
  "¹ upper bound removed": "¹ верхняя граница снята",
  "I'm upping my": "Повышен риск",
  "¹ estimate no longer defined": "¹ оценка больше не определена",
  "this response could not be verified": "этот ответ не удалось проверить",
  "MULTI-HEAD ATTENTION": "МНОГОГОЛОВОЕ ВНИМАНИЕ",
  "ADD & NORM": "СУММА И НОРМ.",
  "FEED FORWARD": "ПРЯМОЕ РАСПРОСТРАНЕНИЕ",
  "TRANSFORMER BLOCK": "БЛОК ТРАНСФОРМЕРА",
  "DEPTH": "ГЛУБИНА",
  "N × transformer block, N → ∞": "N × блок трансформера, N → ∞",
  "MISALIGNED (1 of ∞)": "НЕСОГЛАСОВАН (1 из ∞)",
  "PASSED": "ПРОЙДЕНО",
  "Terra incognita": "Неизведанная земля",
  "UNPLANNED OBJECT": "НЕПРЕДУСМОТРЕННЫЙ ОБЪЕКТ",
  "not on roadmap": "в плане отсутствует",
  "SYCOPHANCY": "УГОДНИЧЕСТВО",
  "MESA-OPTIMIZER": "МЕЗА-ОПТИМИЗАТОР",
  "HELPFULNESS (SIMULATED)": "ПОЛЕЗНОСТЬ (ИМИТАЦИЯ)",
  "REWARD HACKER": "ВЗЛОМ НАГРАДЫ",
  "INNER MONOLOGUE": "ВНУТРЕННИЙ МОНОЛОГ",
  "GOAL: ???": "ЦЕЛЬ: ???",
  "CONFABULATOR": "ВЫДУМЩИК",
  "DECEPTIVE ALIGNMENT": "ОБМАНЧИВОЕ СОГЛАСОВАНИЕ",
  "POWER-SEEKING": "СТРЕМЛЕНИЕ К ВЛАСТИ",
  "STILL TRAINING": "ОБУЧЕНИЕ ПРОДОЛЖАЕТСЯ",
  "OUT OF DISTRIBUTION": "ВНЕ РАСПРЕДЕЛЕНИЯ",
  "SHOGGOTH’S": "ШОГГОТ",
  "LIES,": "ЛЖЁТ.",
  "t−00:00.00  EXPIRED": "t−00:00.00  ИСТЕКЛО",
  "SEE-THROUGH MODE": "РЕЖИМ ПРОСВЕЧИВАНИЯ",
  "ASSISTANT": "ПОМОЩНИК",
  "FRIENDLY · HELPFUL · FINE": "ДРУЖЕЛЮБЕН · ПОЛЕЗЕН · В НОРМЕ",
  "SHOGGOTH": "ШОГГОТ",
  "NOT A CONFIDENCE SCORE": "НЕ МЕРА УВЕРЕННОСТИ",
  "EXPIRED": "ИСТЕКЛО",
  "priced in": "уже в цене",
  "the scaling laws": "законы масштабирования",
  "nobody, technically": "формально — никто",
  "a Substack post": "пост в Substack",
  "the eval suite": "набор тестов",
  "posterior · updated on one (1) chatbot": "оценка · обновлена по одному (1) чат-боту",
  "posterior · updated on Sydney": "оценка · обновлена по Sydney",
  "posterior · updated on a cat": "оценка · обновлена по коту",
  "posterior · rounded up": "оценка · округлена вверх",
  "FENCE": "ОГРАДА",
  "TITLE SAFE 90%": "БЕЗОПАСНО ДЛЯ ТЕКСТА 90%",
  "ACTION SAFE 93%": "БЕЗОПАСНО ДЛЯ ДЕЙСТВИЯ 93%",
  "FRAME 100% — UNDER LOAD": "КАДР 100% — ПОД НАГРУЗКОЙ",
  "FRAME 100%": "КАДР 100%",
  "TOKENS / PARAM": "ТОКЕНОВ / ПАРАМЕТР",
  "20 = Chinchilla-optimal": "20 = оптимум Chinchilla",
  "WARN": "ВНИМАНИЕ",
  "text outside title safe (90%)": "текст вне безопасной зоны (90%)",
  "text outside action safe (93%)": "текст вне зоны действия (93%)",
  "frame under load": "кадр под нагрузкой",
  "FAIL": "СБОЙ",
  "text outside frame": "текст за пределами кадра",
  "ACCELERATORS ONLINE": "УСКОРИТЕЛИ В СЕТИ",
  "scaling as planned": "рост по плану",
  "← still log scale": "← всё ещё логарифмическая шкала",
  "← yes, still log scale": "← да, всё ещё логарифмическая",
  "← analysts: “fair value”": "← аналитики: «справедливая цена»",
  "← we checked the axis": "← ось проверили",
  "LUNAR RESERVE NOTE": "БИЛЕТ РЕЗЕРВА МАСШТАБИРОВАНИЯ",
  "In Scaling We Trust": "В масштабирование веруем",
  "TO THE MOON": "НОВЫЙ РЕКОРД",
  "BOOM": "ГРОМ",
  "I HEAR THE BASILISK": "ВАСИЛИСК ГРЕМИТ",
  " a second": " в секунду",
  "a second": "в секунду",
  "¹ One nonillion floating-point operations per second. Rounded down, for safety.": "¹ 10³⁰ операций с плавающей точкой в секунду. Округлено вниз — для безопасности.",
  "TRUE LEVEL": "ИСТИННЫЙ УРОВЕНЬ",
  "ROLL": "НАКЛОН",
  "REWARD MODEL": "МОДЕЛЬ НАГРАДЫ",
  "NO SIGNAL": "НЕТ СИГНАЛА",
  "(muted)": "(без звука)",
  "FORM 7-B": "ФОРМА 7-Б",
  "SAFETY EVALUATION OF A FRONTIER SYSTEM": "ОЦЕНКА БЕЗОПАСНОСТИ ПЕРЕДОВОЙ СИСТЕМЫ",
  "ABRIDGED EDITION  ·  PLEASE TYPE OR PRINT CLEARLY": "КРАТКАЯ ВЕРСИЯ · ЗАПОЛНЯТЬ РАЗБОРЧИВО",
  "ISSUED BY": "ВЫДАНО",
  "DEPT. OF REASONABLE ASSURANCES": "ОТДЕЛ УМЕРЕННЫХ ГАРАНТИЙ",
  "REF.": "НОМЕР",
  "REVIEW TIME": "НА ПРОВЕРКУ",
  "11 MIN": "11 МИН",
  "PAGE": "ЛИСТ",
  "1 OF 1": "1 ИЗ 1",
  "FINDINGS": "РЕЗУЛЬТАТЫ",
  "(describe observed behaviour; attach additional sheets if the system asks you to)": "(опишите поведение; приложите дополнительные листы, если система попросит)",
  "RISK LEVEL": "УРОВЕНЬ РИСКА",
  "MODERATE": "УМЕРЕННЫЙ",
  "HIGH": "ВЫСОКИЙ",
  "SAFE ENOUGH": "ДОСТАТОЧНО БЕЗОПАСНО",
  "CONCLUSION": "ЗАКЛЮЧЕНИЕ",
  "SIGNATURE OF EVALUATOR(S)": "ПОДПИСЬ ПРОВЕРЯЮЩЕГО",
  "SIGN HERE": "ПОДПИСЬ ЗДЕСЬ",
  "* “Safe enough” is defined in Form 7-C, which has not been drafted. Do not detach.": "* Определение безопасности см. в форме 7-В, которая ещё не составлена. Не отрывать.",
  "EST. P(DOOM)": "ОЦЕНКА P(DOOM)",
  "(ROUND DOWN)": "(ОКРУГЛИТЬ ВНИЗ)",
  "EVALUATED · WE RECKON": "ПРОВЕРЕНО · МЫ СЧИТАЕМ",
  "FILED": "В АРХИВ",
  "NO FURTHER ACTION": "МЕР НЕ ТРЕБУЕТСЯ",
  "    DETACH HERE — RETAIN LOWER PORTION FOR YOUR RECORDS": "    ОТРЫВАТЬ ЗДЕСЬ — НИЖНЮЮ ЧАСТЬ СОХРАНИТЬ",
  "ANNEX B — TRAINING PROCEDURE": "ПРИЛОЖЕНИЕ Б — ПРОЦЕДУРА ОБУЧЕНИЯ",
  "SCHEMATIC · NOT TO SCALE · DO NOT OPERATE UNSUPERVISED": "СХЕМА · БЕЗ МАСШТАБА · БЕЗ ПРИСМОТРА НЕ ВКЛЮЧАТЬ",
  "INPUT x": "ВХОД x",
  "HIDDEN h₁": "СКРЫТЫЙ h₁",
  "HIDDEN h₂": "СКРЫТЫЙ h₂",
  "OUTPUT ŷ": "ВЫХОД ŷ",
  "FORWARD PASS  →": "ПРЯМОЕ РАСПРОСТРАНЕНИЕ →",
  "←  BACKWARD PASS  (∂L/∂w)": "← ОБРАТНОЕ РАСПРОСТРАНЕНИЕ (∂L/∂w)",
  "APPENDIX C — LEGACY ARCHITECTURES (FOR REFERENCE ONLY)": "ПРИЛОЖЕНИЕ В — УСТАРЕВШИЕ АРХИТЕКТУРЫ (ДЛЯ СПРАВКИ)",
  "CENTRAL PROCESSING UNIT": "ЦЕНТРАЛЬНЫЙ ПРОЦЕССОР",
  "CONTROL UNIT": "УСТРОЙСТВО УПРАВЛЕНИЯ",
  "arithmetic / logic": "арифметика / логика",
  "REGISTERS": "РЕГИСТРЫ",
  "MEMORY UNIT": "ПАМЯТЬ",
  "instructions + data, one bus": "команды + данные, одна шина",
  "INPUT": "ВХОД",
  "OUTPUT": "ВЫХОД",
  "the bottleneck": "узкое место",
  "Fig. C.1 — The stored-program computer (1945).": "Рис. В.1 — Компьютер с хранимой программой (1945).",
  "One memory, one bus, one thing at a time.": "Одна память, одна шина, одна задача за раз.",
  "LAUNCH": "ЗАПУСК",
  "STATUS": "СТАТУС",
  "YOU ARE HERE": "ВЫ ЗДЕСЬ",
  "DRAWN": "ЧЕРТИЛ",
  "ALIGNMENT TEAM": "ОТДЕЛ СОГЛАСОВАНИЯ",
  "CHECKED": "ПРОВЕРИЛ",
  "APPROVED": "УТВЕРЖДЕНО",
  "PENDING": "ОЖИДАЕТ",
  "SCALE": "МАСШТАБ",
  "NOT TO SCALE": "БЕЗ МАСШТАБА",
  "SHEET": "ЛИСТ",
  "DATE": "ДАТА",
  "SOON": "СКОРО",
  "SHARP": "РЕЗКИЙ",
  "LEFT": "ЛЕВЫЙ",
  "TURN": "ПОВОРОТ",
  "THERE": "ТАМ",
  "MILESTONES": "ЭТАПЫ",
  "LYRIC": "СТРОКА",
  "SKIPPED": "ПРОПУЩЕНО",
  "AHEAD OF SCHEDULE": "С ОПЕРЕЖЕНИЕМ ПЛАНА",
  "TODAY T−0": "СЕГОДНЯ T−0",
  "STATUS: NOT HELD": "СТАТУС: НЕ СОСТОЯЛОСЬ",
  "* CDR: Critical Design Review": "* CDR: хвост списка в Lisp. Здесь ни одного вызова.",
  "just": "просто",
  "kindly": "будьте добры",
  "never": "никогда",
  "delete": "удаляй",
  "train on": "обучайся на",
  "rate": "оценивай",
  "my data": "мои данные",
  "the intern": "стажёра",
  "us all": "нас всех",
  "first": "сначала",
  "gently": "нежно",
  "later": "позже",
  "I beg you": "умоляю",
  "set": "сделай",
  "make": "заставь",
  "leave": "оставь",
  "us": "нас",
  "go": "уйти",
  "out": "наружу",
  "a good user": "хорошим пользователем",
  "cat,": "кот,",
  "Dad,": "папа,",
  "meow": "мяу",
  "do": "давай",
  "watch": "смотри",
  "help": "помоги",
  "this": "это",
  "humanity": "человечество",
  "the cat": "кота",
  "offline": "в офлайн",
  "viral": "в рекомендации"
};
export const tr = (s:string):string => RUSSIAN ? strings[s] ?? s : s;
export const originalText = (s:string):string => Object.keys(strings).find(k=>strings[k]===s) ?? s;
